### PR TITLE
Review and modify retry policy

### PR DESCRIPTION
**Pull request by rafatower**
Story details: https://app.clubhouse.io/cartoteam/story/124556

### CODE REVIEW

**Review by amiedes — APPROVED** [review]
👍 💪

**Comment by rafatower** [comment]
I'm having this issue while testing locally:
```
central_1             | rake aborted!
central_1             | NameError: uninitialized constant Google::Cloud::PubSub::RetryPolicy
central_1             | /var/lib/gems/2.5.0/bundler/gems/cartodb-common-1bca84990a40/lib/carto/common/message_broker.rb:20:in `<class:MessageBroker>'
central_1             | /var/lib/gems/2.5.0/bundler/gems/cartodb-common-1bca84990a40/lib/carto/common/message_broker.rb:17:in `<module:Common>'
central_1             | /var/lib/gems/2.5.0/bundler/gems/cartodb-common-1bca84990a40/lib/carto/common/message_broker.rb:5:in `<module:Carto>'
```

I think there may be some issue with either autoloader or versions of google pubsub ruby client library. Investigating it...

**Comment by rafatower** [comment]
Now I get this other error:
```
central_1             | rake aborted!
central_1             | LoadError: cannot load such file -- google/cloud/pubsub/retry_policy
central_1             | /var/lib/gems/2.5.0/bundler/gems/cartodb-common-a87ccdcdb88e/lib/carto/common/message_broker.rb:2:in `require'
central_1             | /var/lib/gems/2.5.0/bundler/gems/cartodb-common-a87ccdcdb88e/lib/carto/common/message_broker.rb:2:in `<top (required)>'
```

**Comment by rafatower** [comment]
Essentially the `RetryPolicy` object does not exist in the 1.2.x series: https://googleapis.dev/ruby/google-cloud-pubsub/v1.2.2/Google/Cloud/PubSub.html

I suggest moving to `1.10.0` and if everything goes right, we can consider moving to the 2.x series.

More info here: https://github.com/googleapis/google-cloud-ruby/blob/master/google-cloud-pubsub/CHANGELOG.md

**Pull request merged**
